import { z } from "zod";
import { createTOPSchema } from "./utils.js";

const moviefilein = createTOPSchema({
	pageindex: z.number().optional(),
	file: z.string().optional(),
	reload: z.boolean().optional(),
	reloadpulse: z.boolean().optional(),
	playmode: z.string().optional(),
	play: z.boolean().optional(),
	speed: z.number().optional(),
	cue: z.boolean().optional(),
	cuepulse: z.boolean().optional(),
	cuepoint: z.number().optional(),
	cuepointunit: z.string().optional(),
	cuebehavior: z.string().optional(),
	index: z.number().optional(),
	indexunit: z.string().optional(),
	loopcrossfade: z.number().optional(),
	loopcrossfadeunit: z.string().optional(),
	stepsize: z.number().optional(),
	audioloop: z.string().optional(),
	imageindexing: z.string().optional(),
	timecodeop: z.any().optional(),
	interp: z.boolean().optional(),
	deinterlace: z.string().optional(),
	precedence: z.string().optional(),
	bottomhalfalpha: z.boolean().optional(),
	premultrgbbyalpha: z.string().optional(),
	inputsrgb: z.boolean().optional(),
	loadingerrorimage: z.string().optional(),
	decodepixelformat: z.string().optional(),
	trim: z.boolean().optional(),
	tstart: z.number().optional(),
	tstartunit: z.string().optional(),
	tend: z.number().optional(),
	tendunit: z.string().optional(),
	textendleft: z.string().optional(),
	textendright: z.string().optional(),
	overridesample: z.boolean().optional(),
	samplerate: z.number().optional(),
	prereadframes: z.number().optional(),
	frametimeout: z.number().optional(),
	frametimeoutstrat: z.string().optional(),
	alwaysloadinitial: z.boolean().optional(),
	opentimeout: z.number().optional(),
	updateimage: z.boolean().optional(),
	maxdecodecpus: z.number().optional(),
	highperfread: z.boolean().optional(),
	highperfreadfactor: z.number().optional(),
	hwdecode: z.boolean().optional(),
});

export { moviefilein };
