import { z } from "zod";
import { createTOPSchema } from "./utils.js";

const renderpass = createTOPSchema({
	pageindex: z.number().optional(),
	renderinput: z.any().optional(),
	camera: z.any().optional(),
	geometry: z.any().optional(),
	lights: z.any().optional(),
	cleartocamcolor: z.boolean().optional(),
	cleardepth: z.boolean().optional(),
	possidex: z.boolean().optional(),
	possidey: z.boolean().optional(),
	possidez: z.boolean().optional(),
	negsidex: z.boolean().optional(),
	negsidey: z.boolean().optional(),
	negsidez: z.boolean().optional(),
	transparency: z.string().optional(),
	depthpeel: z.boolean().optional(),
	transpeellayers: z.number().optional(),
	render: z.boolean().optional(),
	dither: z.boolean().optional(),
	coloroutputneeded: z.boolean().optional(),
	drawdepthonly: z.boolean().optional(),
	allowbufblending: z.string().optional(),
	cullface: z.string().optional(),
	overridemat: z.any().optional(),
	polygonoffset: z.boolean().optional(),
	polygonoffsetfactor: z.number().optional(),
	polygonoffsetunits: z.number().optional(),
	overdraw: z.boolean().optional(),
	overdrawlimit: z.number().optional(),
	cropleft: z.number().optional(),
	cropleftunit: z.string().optional(),
	cropright: z.number().optional(),
	croprightunit: z.string().optional(),
	cropbottom: z.number().optional(),
	cropbottomunit: z.string().optional(),
	croptop: z.number().optional(),
	croptopunit: z.string().optional(),
	sampler: z.number().optional(),
	sampler0name: z.string().optional(),
	sampler0top: z.any().optional(),
	sampler0extendu: z.string().optional(),
	sampler0extendv: z.string().optional(),
	sampler0extendw: z.string().optional(),
	sampler0filter: z.string().optional(),
	sampler0anisotropy: z.string().optional(),
	vec: z.number().optional(),
	vec0name: z.string().optional(),
	vec0valuex: z.number().optional(),
	vec0valuey: z.number().optional(),
	vec0valuez: z.number().optional(),
	vec0valuew: z.number().optional(),
});

export { renderpass };
