import { z } from "zod";
import { createDATSchema } from "./utils.js";

export const folder = createDATSchema({
	active: z.boolean().optional().describe("Active"),
	rootfolder: z.string().optional().describe("Root Folder"),
	refresh: z.boolean().optional().describe("Refresh"),
	refreshpulse: z.boolean().optional().describe("Refresh Pulse"),
	asyncupdate: z.boolean().optional().describe("Async Update"),
	nameformat: z.string().optional().describe("Name Format"),
	dateformat: z.string().optional().describe("Date Format"),
	type: z.string().optional().describe("Type"),
	folders: z.string().optional().describe("Folders"),
	names: z.string().optional().describe("Names"),
	allextensions: z.boolean().optional().describe("All Extensions"),
	imageextensions: z.boolean().optional().describe("Image Extensions"),
	movieextensions: z.boolean().optional().describe("Movie Extensions"),
	audioextensions: z.boolean().optional().describe("Audio Extensions"),
	toxextensions: z.boolean().optional().describe("TOX Extensions"),
	toeextensions: z.boolean().optional().describe("TOE Extensions"),
	extensions: z.string().optional().describe("Extensions"),
	subfolders: z.boolean().optional().describe("Subfolders"),
	mindepth: z.number().optional().describe("Min Depth"),
	limitdepth: z.boolean().optional().describe("Limit Depth"),
	maxdepth: z.number().optional().describe("Max Depth"),
	callbacks: z.string().optional().describe("Callbacks"),
	namecol: z.boolean().optional().describe("Name Column"),
	basenamecol: z.boolean().optional().describe("Base Name Column"),
	extensioncol: z.boolean().optional().describe("Extension Column"),
	typecol: z.boolean().optional().describe("Type Column"),
	sizecol: z.boolean().optional().describe("Size Column"),
	depthcol: z.boolean().optional().describe("Depth Column"),
	foldercol: z.boolean().optional().describe("Folder Column"),
	pathcol: z.boolean().optional().describe("Path Column"),
	relpathcol: z.boolean().optional().describe("Relative Path Column"),
	datecreatedcol: z.boolean().optional().describe("Date Created Column"),
	datemodifiedcol: z.boolean().optional().describe("Date Modified Column"),
	dateaccessedcol: z.boolean().optional().describe("Date Accessed Column"),
});
