import { z } from "zod";
import { createDATSchema } from "./utils.js";

export const opfind = createDATSchema({
	activecook: z.string().optional().describe("Active Cook"),
	cookpulse: z.boolean().optional().describe("Cook Pulse"),
	component: z.string().optional().describe("Component"),
	includecomponent: z.boolean().optional().describe("Include Component"),
	includewired: z.boolean().optional().describe("Include Wired"),
	mindepth: z.number().optional().describe("Min Depth"),
	limitmaxdepth: z.boolean().optional().describe("Limit Max Depth"),
	maxdepth: z.number().optional().describe("Max Depth"),
	limitmaxops: z.boolean().optional().describe("Limit Max Ops"),
	maxops: z.number().optional().describe("Max Ops"),
	objects: z.boolean().optional().describe("Objects"),
	panels: z.boolean().optional().describe("Panels"),
	other: z.boolean().optional().describe("Other"),
	tops: z.boolean().optional().describe("TOPs"),
	chops: z.boolean().optional().describe("CHOPs"),
	sops: z.boolean().optional().describe("SOPs"),
	mats: z.boolean().optional().describe("MATs"),
	dats: z.boolean().optional().describe("DATs"),
	utility: z.boolean().optional().describe("Utility"),
	casesensitive: z.boolean().optional().describe("Case Sensitive"),
	combinefilters: z.string().optional().describe("Combine Filters"),
	customcombine: z.string().optional().describe("Custom Combine"),
	namefilter: z.string().optional().describe("Name Filter"),
	typefilter: z.string().optional().describe("Type Filter"),
	parentshortcutfilter: z
		.string()
		.optional()
		.describe("Parent Shortcut Filter"),
	opshortcutfilter: z.string().optional().describe("Op Shortcut Filter"),
	pathfilter: z.string().optional().describe("Path Filter"),
	parentfilter: z.string().optional().describe("Parent Filter"),
	excludefilter: z.string().optional().describe("Exclude Filter"),
	wirepathfilter: z.string().optional().describe("Wire Path Filter"),
	commentfilter: z.string().optional().describe("Comment Filter"),
	tagsfilter: z.string().optional().describe("Tags Filter"),
	textfilter: z.string().optional().describe("Text Filter"),
	parnamefilter: z.string().optional().describe("Par Name Filter"),
	parvaluefilter: z.string().optional().describe("Par Value Filter"),
	parexpressionfilter: z.string().optional().describe("Par Expression Filter"),
	parnondefaultonly: z.boolean().optional().describe("Par Non Default Only"),
	legacycols: z.boolean().optional().describe("Legacy Cols"),
	idcol: z.boolean().optional().describe("ID Column"),
	namecol: z.boolean().optional().describe("Name Column"),
	typecol: z.boolean().optional().describe("Type Column"),
	parentshortcutcol: z.boolean().optional().describe("Parent Shortcut Column"),
	opshortcutcol: z.boolean().optional().describe("Op Shortcut Column"),
	pathcol: z.boolean().optional().describe("Path Column"),
	relpathcol: z.boolean().optional().describe("Relative Path Column"),
	parentpath: z.boolean().optional().describe("Parent Path"),
	wirepathcol: z.boolean().optional().describe("Wire Path Column"),
	depthcol: z.boolean().optional().describe("Depth Column"),
	cooktimescol: z.boolean().optional().describe("Cook Times Column"),
	tagscol: z.boolean().optional().describe("Tags Column"),
	genprop: z.boolean().optional().describe("Gen Prop"),
	cputime: z.boolean().optional().describe("CPU Time"),
	gputime: z.boolean().optional().describe("GPU Time"),
	cpumem: z.boolean().optional().describe("CPU Memory"),
	gpumem: z.boolean().optional().describe("GPU Memory"),
	children: z.boolean().optional().describe("Children"),
	callbacks: z.string().optional().describe("Callbacks"),
	convertbool: z.boolean().optional().describe("Convert Bool"),
	convertnone: z.boolean().optional().describe("Convert None"),
});
