import { z } from "zod";
import { createDATSchema } from "./utils.js";

export const parameter = createDATSchema({
	ops: z.string().optional().describe("Ops"),
	pargroups: z.string().optional().describe("Parameter Groups"),
	parameters: z.string().optional().describe("Parameters"),
	pages: z.string().optional().describe("Pages"),
	includeopname: z.boolean().optional().describe("Include Op Name"),
	sortmethod: z.string().optional().describe("Sort Method"),
	renamefrom: z.string().optional().describe("Rename From"),
	renameto: z.string().optional().describe("Rename To"),
	custom: z.boolean().optional().describe("Custom"),
	builtin: z.boolean().optional().describe("Built-in"),
	header: z.boolean().optional().describe("Header"),
	name: z.boolean().optional().describe("Name"),
	label: z.boolean().optional().describe("Label"),
	value: z.boolean().optional().describe("Value"),
	eval: z.boolean().optional().describe("Eval"),
	constant: z.boolean().optional().describe("Constant"),
	expression: z.boolean().optional().describe("Expression"),
	export: z.boolean().optional().describe("Export"),
	bind: z.boolean().optional().describe("Bind"),
	mode: z.boolean().optional().describe("Mode"),
	style: z.boolean().optional().describe("Style"),
	pargroupname: z.boolean().optional().describe("Parameter Group Name"),
	tupletname: z.boolean().optional().describe("Tuplet Name"),
	size: z.boolean().optional().describe("Size"),
	path: z.boolean().optional().describe("Path"),
	menuindex: z.boolean().optional().describe("Menu Index"),
	page: z.boolean().optional().describe("Page"),
	sequence: z.boolean().optional().describe("Sequence"),
	blockindex: z.boolean().optional().describe("Block Index"),
	basename: z.boolean().optional().describe("Base Name"),
	numblocks: z.boolean().optional().describe("Num Blocks"),
	minmax: z.boolean().optional().describe("Min/Max"),
	clampminmax: z.boolean().optional().describe("Clamp Min/Max"),
	normminmax: z.boolean().optional().describe("Norm Min/Max"),
	default: z.boolean().optional().describe("Default"),
	enabled: z.boolean().optional().describe("Enabled"),
	readonly: z.boolean().optional().describe("Read Only"),
	section: z.boolean().optional().describe("Section"),
	menunames: z.boolean().optional().describe("Menu Names"),
	menulabels: z.boolean().optional().describe("Menu Labels"),
});
