import { z } from "zod";
import { createDATSchema } from "./utils.js";

export const renderpick = createDATSchema({
	strategy: z.string().optional().describe("Strategy"),
	clearprev: z.boolean().optional().describe("Clear Previous"),
	responsetime: z.string().optional().describe("Response Time"),
	pickradius: z.number().optional().describe("Pick Radius"),
	pickradstep: z.number().optional().describe("Pick Radius Step"),
	pickcirstep: z.number().optional().describe("Pick Circle Step"),
	rendertop: z.any().optional().describe("Render TOP"),
	custompickcameras: z.any().optional().describe("Custom Pick Cameras"),
	allowmulticamera: z.boolean().optional().describe("Allow Multi Camera"),
	usepickableflags: z.boolean().optional().describe("Use Pickable Flags"),
	includenonpickable: z.boolean().optional().describe("Include Non Pickable"),
	mergeinputdat: z.boolean().optional().describe("Merge Input DAT"),
	activatecallbacks: z.boolean().optional().describe("Activate Callbacks"),
	callbacks: z.string().optional().describe("Callbacks"),
	position: z.string().optional().describe("Position"),
	normal: z.string().optional().describe("Normal"),
	referenceobj: z.any().optional().describe("Reference Object"),
	color: z.boolean().optional().describe("Color"),
	uv: z.boolean().optional().describe("UV"),
	depth: z.boolean().optional().describe("Depth"),
	instanceid: z.boolean().optional().describe("Instance ID"),
	customattrib1: z.string().optional().describe("Custom Attribute 1"),
	customattrib1type: z.string().optional().describe("Custom Attribute 1 Type"),
	customattrib2: z.string().optional().describe("Custom Attribute 2"),
	customattrib2type: z.string().optional().describe("Custom Attribute 2 Type"),
	customattrib3: z.string().optional().describe("Custom Attribute 3"),
	customattrib3type: z.string().optional().describe("Custom Attribute 3 Type"),
	customattrib4: z.string().optional().describe("Custom Attribute 4"),
	customattrib4type: z.string().optional().describe("Custom Attribute 4 Type"),
});
