import { z } from "zod";
import { createTOPSchema } from "./index.js";

const circle = createTOPSchema({
	pageindex: z.number().optional(),
	radiusx: z.number().optional(),
	radiusy: z.number().optional(),
	radiusunit: z.string().optional(),
	rotate: z.number().optional(),
	centerx: z.number().optional(),
	centery: z.number().optional(),
	centerunit: z.string().optional(),
	justifyh: z.string().optional(),
	justifyv: z.string().optional(),
	fillcolorr: z.number().optional(),
	fillcolorg: z.number().optional(),
	fillcolorb: z.number().optional(),
	fillalpha: z.number().optional(),
	borderr: z.number().optional(),
	borderg: z.number().optional(),
	borderb: z.number().optional(),
	borderalpha: z.number().optional(),
	bgcolorr: z.number().optional(),
	bgcolorg: z.number().optional(),
	bgcolorb: z.number().optional(),
	bgalpha: z.number().optional(),
	premultrgbbyalpha: z.boolean().optional(),
	borderwidth: z.number().optional(),
	borderwidthunit: z.string().optional(),
	borderoffset: z.number().optional(),
	beginarcangle: z.number().optional(),
	endarcangle: z.number().optional(),
	antialias: z.boolean().optional(),
	ispolygon: z.boolean().optional(),
	sides: z.number().optional(),
	softness: z.number().optional(),
	softnessunit: z.number().optional(),
	softnessoffset: z.number().optional(),
	softnesstype: z.string().optional(),
	combineinput: z.string().optional(),
	operand: z.string().optional(),
	swaporder: z.boolean().optional(),
});

export { circle };
