import { z } from "zod";
import { createTOPSchema } from "./index.js";

const moviefileout = createTOPSchema({
	pageindex: z.number().optional(),
	type: z.string().optional(),
	videocodec: z.string().optional(),
	videocodectype: z.string().optional(),
	imagefiletype: z.string().optional(),
	uniquesuff: z.boolean().optional(),
	n: z.number().optional(),
	file: z.string().optional(),
	moviepixelformat: z.string().optional(),
	audiochop: z.any().optional(),
	audiocodec: z.string().optional(),
	audiobitrate: z.string().optional(),
	quality: z.number().optional(),
	fps: z.number().optional(),
	limitlength: z.boolean().optional(),
	length: z.number().optional(),
	lengthunit: z.string().optional(),
	record: z.boolean().optional(),
	pause: z.boolean().optional(),
	addframe: z.boolean().optional(),
	maxthread: z.number().optional(),
	headerdat: z.any().optional(),
	pointcloud: z.boolean().optional(),
	input: z.number().optional(),
	input0top: z.any().optional(),
	input0r: z.string().optional(),
	input0g: z.string().optional(),
	input0b: z.string().optional(),
	input0a: z.string().optional(),
	stallforopen: z.boolean().optional(),
	profile: z.string().optional(),
	preset: z.string().optional(),
	bitratemode: z.string().optional(),
	avgbitrate: z.number().optional(),
	peakbitrate: z.number().optional(),
	keyframeinterval: z.number().optional(),
	maxbframes: z.number().optional(),
	motionpredict: z.string().optional(),
	frameslicing: z.boolean().optional(),
	numslices: z.number().optional(),
	entropymode: z.string().optional(),
	secondarycompression: z.boolean().optional(),
	encodetestmode: z.boolean().optional(),
	mipmaps: z.boolean().optional(),
});

export { moviefileout };
