import { z } from "zod";
import { createTOPSchema } from "./index.js";

const noise = createTOPSchema({
	pageindex: z.number().optional(),
	type: z.string().optional(),
	seed: z.number().optional(),
	period: z.number().optional(),
	harmon: z.number().optional(),
	spread: z.number().optional(),
	gain: z.number().optional(),
	rough: z.number().optional(),
	exp: z.number().optional(),
	amp: z.number().optional(),
	offset: z.number().optional(),
	mono: z.boolean().optional(),
	aspectcorrect: z.boolean().optional(),
	xord: z.string().optional(),
	rord: z.string().optional(),
	tx: z.number().optional(),
	ty: z.number().optional(),
	tz: z.number().optional(),
	rx: z.number().optional(),
	ry: z.number().optional(),
	rz: z.number().optional(),
	sx: z.number().optional(),
	sy: z.number().optional(),
	sz: z.number().optional(),
	px: z.number().optional(),
	py: z.number().optional(),
	pz: z.number().optional(),
	t4d: z.number().optional(),
	s4d: z.number().optional(),
	rgb: z.string().optional(),
	inputscale: z.number().optional(),
	noisescale: z.number().optional(),
	alpha: z.string().optional(),
	dither: z.boolean().optional(),
	derivative: z.boolean().optional(),
});

export { noise };
