import { z } from "zod";
import { createTOPSchema } from "./index.js";

const videodevicein = createTOPSchema({
	pageindex: z.number().optional(),
	active: z.boolean().optional(),
	driver: z.string().optional(),
	device: z.string().optional(),
	allowfallback: z.boolean().optional(),
	specifyip: z.boolean().optional(),
	ip: z.string().optional(),
	options: z.boolean().optional(),
	deinterlace: z.string().optional(),
	precedence: z.string().optional(),
	channel: z.number().optional(),
	signalformat: z.string().optional(),
	quadlink: z.boolean().optional(),
	inputpixelformat: z.string().optional(),
	transfermode: z.string().optional(),
	memorymode: z.string().optional(),
	syncinputs: z.boolean().optional(),
	syncgroupindex: z.number().optional(),
	maxsyncoffset: z.number().optional(),
	synctimeout: z.number().optional(),
	resetstats: z.boolean().optional(),
	preset: z.string().optional(),
	autoge: z.boolean().optional(),
	autogebias: z.number().optional(),
	autogelevel: z.number().optional(),
	maxgain: z.number().optional(),
	maxexposure: z.number().optional(),
	gain: z.number().optional(),
	exposure: z.number().optional(),
	cgamma: z.number().optional(),
	lgamma: z.number().optional(),
	limitfps: z.boolean().optional(),
	limitedfps: z.number().optional(),
	capture: z.boolean().optional(),
	capturepulse: z.boolean().optional(),
	autowb: z.boolean().optional(),
	wbcoeffsr: z.number().optional(),
	wbcoeffsg: z.number().optional(),
	wbcoeffsb: z.number().optional(),
	custombandwidth: z.string().optional(),
	bandwidthlimit: z.number().optional(),
	camerabitdepth: z.string().optional(),
	gpudemosaic: z.boolean().optional(),
});

export { videodevicein };
