import { z } from "zod";
import { createSOPSchema } from "./utils.js";

const basis = createSOPSchema({
	group: z.string().optional().describe("Group"),
	ubasis: z.boolean().optional().describe("U Basis"),
	uparmtype: z.string().optional().describe("U Parameter Type"),
	uknots: z.string().optional().describe("U Knots"),
	uread: z.boolean().optional().describe("U Read"),
	urange1: z.number().optional().describe("U Range 1"),
	urange2: z.number().optional().describe("U Range 2"),
	ubias: z.number().optional().describe("U Bias"),
	uconcat: z.boolean().optional().describe("U Concatenate"),
	udoorigin: z.boolean().optional().describe("U Do Origin"),
	uorigin: z.number().optional().describe("U Origin"),
	udolength: z.boolean().optional().describe("U Do Length"),
	ulength: z.number().optional().describe("U Length"),
	udoscale: z.boolean().optional().describe("U Do Scale"),
	uscale: z.number().optional().describe("U Scale"),
	uraise: z.boolean().optional().describe("U Raise"),
	orderu: z.number().optional().describe("Order U"),
	vbasis: z.boolean().optional().describe("V Basis"),
	vparmtype: z.string().optional().describe("V Parameter Type"),
	vknots: z.string().optional().describe("V Knots"),
	vread: z.boolean().optional().describe("V Read"),
	vrange1: z.number().optional().describe("V Range 1"),
	vrange2: z.number().optional().describe("V Range 2"),
	vbias: z.number().optional().describe("V Bias"),
	vconcat: z.boolean().optional().describe("V Concatenate"),
	vdoorigin: z.boolean().optional().describe("V Do Origin"),
	vorigin: z.number().optional().describe("V Origin"),
	vdolength: z.boolean().optional().describe("V Do Length"),
	vlength: z.number().optional().describe("V Length"),
	vdoscale: z.boolean().optional().describe("V Do Scale"),
	vscale: z.number().optional().describe("V Scale"),
	vraise: z.boolean().optional().describe("V Raise"),
	orderv: z.number().optional().describe("Order V"),
});

export { basis };
