import { z } from "zod";
import { createSOPSchema } from "./utils.js";

const point = createSOPSchema({
	group: z.string().optional().describe("Group"),
	doclr: z.string().optional().describe("Do Color"),
	diffr: z.number().optional().describe("Diffuse Red"),
	diffg: z.number().optional().describe("Diffuse Green"),
	diffb: z.number().optional().describe("Diffuse Blue"),
	alpha: z.number().optional().describe("Alpha"),
	premultrgbbyalpha: z
		.boolean()
		.optional()
		.describe("Premultiply RGB by Alpha"),
	donml: z.string().optional().describe("Do Normal"),
	nx: z.number().optional().describe("Normal X"),
	ny: z.number().optional().describe("Normal Y"),
	nz: z.number().optional().describe("Normal Z"),
	douvw: z.string().optional().describe("Do UVW"),
	mapu: z.number().optional().describe("Map U"),
	mapv: z.number().optional().describe("Map V"),
	mapw: z.number().optional().describe("Map W"),
	dowidth: z.string().optional().describe("Do Width"),
	dopscale: z.string().optional().describe("Do Point Scale"),
	attr: z.number().optional().describe("Attribute"),
	attr0name: z.string().optional().describe("Attribute 0 Name"),
	attr0type: z.string().optional().describe("Attribute 0 Type"),
	attr0value1: z.number().optional().describe("Attribute 0 Value 1"),
	attr0value2: z.number().optional().describe("Attribute 0 Value 2"),
	attr0value3: z.number().optional().describe("Attribute 0 Value 3"),
	attr0value4: z.number().optional().describe("Attribute 0 Value 4"),
	domass: z.string().optional().describe("Do Mass"),
	mass: z.number().optional().describe("Mass"),
	drag: z.number().optional().describe("Drag"),
	dotension: z.string().optional().describe("Do Tension"),
	dospringk: z.string().optional().describe("Do Spring Constant"),
	dovel: z.string().optional().describe("Do Velocity"),
	doup: z.string().optional().describe("Do Up"),
	doradius: z.string().optional().describe("Do Radius"),
	radiusf: z.number().optional().describe("Radius Factor"),
	doscale: z.string().optional().describe("Do Scale"),
	scalef: z.number().optional().describe("Scale Factor"),
	doradialf: z.string().optional().describe("Do Radial Factor"),
	radialf: z.number().optional().describe("Radial Factor"),
	donormalf: z.string().optional().describe("Do Normal Factor"),
	normalf: z.number().optional().describe("Normal Factor"),
	doedgef: z.string().optional().describe("Do Edge Factor"),
	edgef: z.number().optional().describe("Edge Factor"),
	dodirf: z.string().optional().describe("Do Direction Factor"),
	dirfx: z.number().optional().describe("Direction Factor X"),
	dirfy: z.number().optional().describe("Direction Factor Y"),
	dirfz: z.number().optional().describe("Direction Factor Z"),
});

export { point };
