info:
  description: OpenAPI schema for generating TouchDesigner API client code
  title: TouchDesigner API
  version: 0.2.12

openapi: 3.0.0

servers:
  - url: '{baseUrl}'
    variables:
      baseUrl:
        default: http://localhost:9981

paths:
  /api/td/server/td:
    $ref: ./paths/api/td/server/td.yml
  /api/td/server/exec:
    $ref: ./paths/api/td/server/exec.yml
  /api/nodes:
    $ref: ./paths/api/nodes/list.yml
  /api/nodes/detail:
    $ref: ./paths/api/nodes/detail.yml
  /api/td/classes:
    $ref: ./paths/api/td/classes/list.yml
  /api/td/classes/{className}:
    $ref: ./paths/api/td/classes/details.yml
  /api/td/nodes/exec:
    $ref: ./paths/api/td/nodes/exec.yml

components:
  schemas:
    TdNode:
      $ref: ./components/schemas/TdNode.yml
    TdNodeFamilyType:
      $ref: ./components/schemas/TdNodeFamilyType.yml
    TdPythonClassInfo:
      $ref: ./components/schemas/TdPythonClassInfo.yml
    TdPythonMethodInfo:
      $ref: ./components/schemas/TdPythonMethodInfo.yml
    TdPythonPropertyInfo:
      $ref: ./components/schemas/TdPythonPropertyInfo.yml
    TdPythonClassDetails:
      $ref: ./components/schemas/TdPythonClassDetails.yml
