import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const importselect = createCHOPSchema({
	parent: z.any().nullable().optional().describe("Parent"),
	taketype: z.string().optional().describe("Take Type"),
	blendshape: z.string().optional().describe("Blend Shape"),
	reload: z.boolean().optional().describe("Reload"),
	useparentanim: z.boolean().optional().describe("Use Parent Animation"),
	animation: z.string().optional().describe("Animation"),
	shiftanimationstart: z.boolean().optional().describe("Shift Animation Start"),
	sampleratemode: z.string().optional().describe("Sample Rate Mode"),
	samplerate: z.number().optional().describe("Sample Rate"),
	playmode: z.string().optional().describe("Play Mode"),
	index: z.number().optional().describe("Index"),
	indexunit: z.string().optional().describe("Index Unit"),
	play: z.boolean().optional().describe("Play"),
	speed: z.number().optional().describe("Speed"),
	trim: z.boolean().optional().describe("Trim"),
	tstart: z.number().optional().describe("Start"),
	tstartunit: z.string().optional().describe("Start Unit"),
	tend: z.number().optional().describe("End"),
	tendunit: z.string().optional().describe("End Unit"),
	cue: z.boolean().optional().describe("Cue"),
	cuepulse: z.boolean().optional().describe("Cue Pulse"),
	cuepoint: z.number().optional().describe("Cue Point"),
	cuepointunit: z.string().optional().describe("Cue Point Unit"),
	textendleft: z.string().optional().describe("Time Extend Left"),
	textendright: z.string().optional().describe("Time Extend Right"),
});
