import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const kinect = createCHOPSchema({
	pageindex: z.number().describe("Page Index"),
	active: z.boolean().describe("Active"),
	hwversion: z.string().describe("Hardware Version"),
	sensor: z.string().describe("Sensor"),
	skeleton: z.string().describe("Skeleton"),
	maxplayers: z.number().describe("Max Players"),
	interactions: z.boolean().describe("Interactions"),
	relbonerotations: z.boolean().describe("Relative Bone Rotations"),
	absbonerotations: z.boolean().describe("Absolute Bone Rotations"),
	bonelengths: z.boolean().describe("Bone Lengths"),
	unrollbones: z.boolean().describe("Unroll Bones"),
	worldspace: z.boolean().describe("World Space"),
	colorspace: z.boolean().describe("Color Space"),
	depthspace: z.boolean().describe("Depth Space"),
	facetracking: z.boolean().describe("Face Tracking"),
	statuschans: z.boolean().describe("Status Channels"),
	neardepthmode: z.boolean().describe("Near Depth Mode"),
	flipskelu: z.boolean().describe("Flip Skeleton U"),
	flipfaceu: z.boolean().describe("Flip Face U"),
	jointsmoothing: z.boolean().describe("Joint Smoothing"),
	smoothing: z.number().describe("Smoothing"),
	correction: z.number().describe("Correction"),
	prediction: z.number().describe("Prediction"),
	jitterrad: z.number().describe("Jitter Radius"),
	maxdevrad: z.number().describe("Max Deviation Radius"),
	rotationsmoothing: z.number().describe("Rotation Smoothing"),
});
