import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const midiout = createCHOPSchema({
	active: z.boolean().optional().describe("Active"),
	destination: z.string().optional().describe("Destination"),
	device: z.string().optional().describe("Device"),
	id: z.string().optional().describe("ID"),
	onebased: z.boolean().optional().describe("One Based"),
	file: z.string().optional().describe("File"),
	writefile: z.boolean().optional().describe("Write File"),
	prefix: z.string().optional().describe("Prefix"),
	cookalways: z.boolean().optional().describe("Cook Always"),
	autonoteoff: z.string().optional().describe("Auto Note Off"),
	reset: z.boolean().optional().describe("Reset"),
	volumeoff: z.boolean().optional().describe("Volume Off"),
	volumeon: z.boolean().optional().describe("Volume On"),
	startstop: z.boolean().optional().describe("Start/Stop"),
	sendmtc: z.boolean().optional().describe("Send MTC"),
	timecodeop: z.any().nullable().optional().describe("Timecode OP"),
	notename: z.string().optional().describe("Note Name"),
	aftername: z.string().optional().describe("Aftertouch Name"),
	pressname: z.string().optional().describe("Pressure Name"),
	notenorm: z.string().optional().describe("Note Normalize"),
	pitchname: z.string().optional().describe("Pitch Name"),
	controlname: z.string().optional().describe("Control Name"),
	controlformat: z.string().optional().describe("Control Format"),
	controlnorm: z.string().optional().describe("Control Normalize"),
	progname: z.string().optional().describe("Program Name"),
	barname: z.string().optional().describe("Bar Name"),
	barticks: z.number().optional().describe("Bar Ticks"),
});
