import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const midiin = createCHOPSchema({
	active: z.boolean().optional().describe("Active"),
	source: z.string().optional().describe("Source"),
	device: z.string().optional().describe("Device"),
	id: z.string().optional().describe("ID"),
	file: z.string().optional().describe("File"),
	entire: z.boolean().optional().describe("Entire"),
	resetchannels: z.boolean().optional().describe("Reset Channels"),
	resetchannelspulse: z.boolean().optional().describe("Reset Channels Pulse"),
	reset: z.boolean().optional().describe("Reset"),
	resetpulse: z.boolean().optional().describe("Reset Pulse"),
	simplified: z.boolean().optional().describe("Simplified"),
	preservepulses: z.boolean().optional().describe("Preserve Pulses"),
	sortchannels: z.boolean().optional().describe("Sort Channels"),
	sortchannelspulse: z.boolean().optional().describe("Sort Channels Pulse"),
	onebased: z.boolean().optional().describe("One Based"),
	channel: z.string().optional().describe("Channel"),
	prefix: z.string().optional().describe("Prefix"),
	recordtype: z.string().optional().describe("Record Type"),
	record: z.boolean().optional().describe("Record"),
	notename: z.string().optional().describe("Note Name"),
	notescope: z.string().optional().describe("Note Scope"),
	notemeth: z.string().optional().describe("Note Method"),
	velocity: z.string().optional().describe("Velocity"),
	velname: z.string().optional().describe("Velocity Name"),
	aftername: z.string().optional().describe("Aftertouch Name"),
	pressname: z.string().optional().describe("Pressure Name"),
	notenorm: z.string().optional().describe("Note Normalize"),
	pitchname: z.string().optional().describe("Pitch Name"),
	controlname: z.string().optional().describe("Control Name"),
	controltype: z.string().optional().describe("Control Type"),
	controlind: z.string().optional().describe("Control Index"),
	format: z.string().optional().describe("Format"),
	norm: z.string().optional().describe("Normalize"),
	unwrap: z.boolean().optional().describe("Unwrap"),
	progname: z.string().optional().describe("Program Name"),
	pulsename: z.string().optional().describe("Pulse Name"),
	rampname: z.string().optional().describe("Ramp Name"),
	timerperiod: z.string().optional().describe("Timer Period"),
	timerstart: z.string().optional().describe("Timer Start"),
	ticks: z.number().optional().describe("Ticks"),
	barname: z.string().optional().describe("Bar Name"),
	barperiod: z.string().optional().describe("Bar Period"),
	barstart: z.string().optional().describe("Bar Start"),
	barmsg: z.string().optional().describe("Bar Message"),
	songpos: z.string().optional().describe("Song Position"),
	sysex: z.number().optional().describe("System Exclusive"),
	sysex0name: z.string().optional().describe("System Exclusive 0 Name"),
	sysex0msg: z.string().optional().describe("System Exclusive 0 Message"),
	start: z.number().optional().describe("Start"),
	startunit: z.string().optional().describe("Start Unit"),
	end: z.number().optional().describe("End"),
	endunit: z.string().optional().describe("End Unit"),
	rate: z.number().optional().describe("Rate"),
	left: z.string().optional().describe("Left Boundary"),
	right: z.string().optional().describe("Right Boundary"),
	defval: z.number().optional().describe("Default Value"),
});
