import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const perform = createCHOPSchema({
	fps: z.boolean().optional().describe("FPS"),
	msec: z.boolean().optional().describe("Milliseconds"),
	cpumsec: z.boolean().optional().describe("CPU Milliseconds"),
	cook: z.boolean().optional().describe("Cook"),
	droppedframes: z.boolean().optional().describe("Dropped Frames"),
	mvreadahead: z.boolean().optional().describe("Movie Read Ahead"),
	gpumemused: z.boolean().optional().describe("GPU Memory Used"),
	totalgpumem: z.boolean().optional().describe("Total GPU Memory"),
	activeops: z.boolean().optional().describe("Active Operators"),
	deactivatedops: z.boolean().optional().describe("Deactivated Operators"),
	totalops: z.boolean().optional().describe("Total Operators"),
	cpumemused: z.boolean().optional().describe("CPU Memory Used"),
	cookstate: z.boolean().optional().describe("Cook State"),
	cookrealtime: z.boolean().optional().describe("Cook Real Time"),
	cookrate: z.boolean().optional().describe("Cook Rate"),
	timeslicestep: z.boolean().optional().describe("Time Slice Step"),
	timeslicemsec: z.boolean().optional().describe("Time Slice Milliseconds"),
	performmode: z.boolean().optional().describe("Perform Mode"),
	performfocus: z.boolean().optional().describe("Perform Focus"),
	gputemp: z.boolean().optional().describe("GPU Temperature"),
	aclinestatus: z.boolean().optional().describe("AC Line Status"),
	batterycharging: z.boolean().optional().describe("Battery Charging"),
	batterylife: z.boolean().optional().describe("Battery Life"),
	batterytime: z.boolean().optional().describe("Battery Time"),
	activeexpressions: z.boolean().optional().describe("Active Expressions"),
	optimizedexpression: z.boolean().optional().describe("Optimized Expression"),
	cachedexpressions: z.boolean().optional().describe("Cached Expressions"),
});
