import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const tablet = createCHOPSchema({
	xcoord: z.string().optional().describe("X Coordinate"),
	ycoord: z.string().optional().describe("Y Coordinate"),
	pressure: z.string().optional().describe("Pressure"),
	xtilt: z.string().optional().describe("X Tilt"),
	ytilt: z.string().optional().describe("Y Tilt"),
	tanpressure: z.string().optional().describe("Tangent Pressure"),
	zcoord: z.string().optional().describe("Z Coordinate"),
	rotation: z.string().optional().describe("Rotation"),
	button1: z.string().optional().describe("Button 1"),
	button2: z.string().optional().describe("Button 2"),
	button3: z.string().optional().describe("Button 3"),
	button4: z.string().optional().describe("Button 4"),
	button5: z.string().optional().describe("Button 5"),
	xcoord2: z.string().optional().describe("X Coordinate 2"),
	ycoord2: z.string().optional().describe("Y Coordinate 2"),
	pressure2: z.string().optional().describe("Pressure 2"),
	xtilt2: z.string().optional().describe("X Tilt 2"),
	ytilt2: z.string().optional().describe("Y Tilt 2"),
	tanpressure2: z.string().optional().describe("Tangent Pressure 2"),
	zcoord2: z.string().optional().describe("Z Coordinate 2"),
	rotation2: z.string().optional().describe("Rotation 2"),
	button21: z.string().optional().describe("Button 2-1"),
	button22: z.string().optional().describe("Button 2-2"),
	button23: z.string().optional().describe("Button 2-3"),
	button24: z.string().optional().describe("Button 2-4"),
	button25: z.string().optional().describe("Button 2-5"),
	active: z.string().optional().describe("Active"),
	rate: z.number().optional().describe("Rate"),
	left: z.string().optional().describe("Left Boundary"),
	right: z.string().optional().describe("Right Boundary"),
	defval: z.number().optional().describe("Default Value"),
});
