import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const timecode = createCHOPSchema({
	smpte: z.boolean().optional().describe("SMPTE"),
	mode: z.string().optional().describe("Mode"),
	rate: z.number().optional().describe("Rate"),
	dropframe: z.string().optional().describe("Drop Frame"),
	index: z.number().optional().describe("Index"),
	indexunit: z.string().optional().describe("Index Unit"),
	timecodestr: z.string().optional().describe("Timecode String"),
	frame: z.number().optional().describe("Frame"),
	second: z.number().optional().describe("Second"),
	minute: z.number().optional().describe("Minute"),
	hour: z.number().optional().describe("Hour"),
	init: z.boolean().optional().describe("Initialize"),
	start: z.boolean().optional().describe("Start"),
	play: z.boolean().optional().describe("Play"),
	timecodeobj: z.string().optional().describe("Timecode Object"),
	chop: z.any().nullable().optional().describe("CHOP"),
	op: z.any().nullable().optional().describe("OP"),
	customlength: z.boolean().optional().describe("Custom Length"),
	length: z.number().optional().describe("Length"),
	lengthunits: z.string().optional().describe("Length Units"),
	cycle: z.boolean().optional().describe("Cycle"),
	negativechan: z.boolean().optional().describe("Negative Channel"),
	framechan: z.boolean().optional().describe("Frame Channel"),
	secondchan: z.boolean().optional().describe("Second Channel"),
	minutechan: z.boolean().optional().describe("Minute Channel"),
	hourchan: z.boolean().optional().describe("Hour Channel"),
	totalseconds: z.boolean().optional().describe("Total Seconds"),
	totalframes: z.boolean().optional().describe("Total Frames"),
	dropframechan: z.boolean().optional().describe("Drop Frame Channel"),
	fpschan: z.boolean().optional().describe("FPS Channel"),
	countdown: z.boolean().optional().describe("Countdown"),
});
