import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const timer = createCHOPSchema({
	active: z.string().optional().describe("Active"),
	timecontrol: z.string().optional().describe("Time Control"),
	deferpars: z.boolean().optional().describe("Defer Parameters"),
	initialize: z.boolean().optional().describe("Initialize"),
	start: z.boolean().optional().describe("Start"),
	lengthtype: z.string().optional().describe("Length Type"),
	length: z.number().optional().describe("Length"),
	lengthunits: z.string().optional().describe("Length Units"),
	delay: z.number().optional().describe("Delay"),
	delayunits: z.string().optional().describe("Delay Units"),
	play: z.boolean().optional().describe("Play"),
	speed: z.number().optional().describe("Speed"),
	cue: z.boolean().optional().describe("Cue"),
	cuepulse: z.boolean().optional().describe("Cue Pulse"),
	cuepoint: z.number().optional().describe("Cue Point"),
	cueunits: z.string().optional().describe("Cue Units"),
	cycle: z.boolean().optional().describe("Cycle"),
	cyclelimit: z.boolean().optional().describe("Cycle Limit"),
	maxcycles: z.number().optional().describe("Max Cycles"),
	cycleendalert: z.number().optional().describe("Cycle End Alert"),
	notifyunits: z.string().optional().describe("Notify Units"),
	exitendcycle: z.boolean().optional().describe("Exit End Cycle"),
	gotoendcycle: z.boolean().optional().describe("Go To End Cycle"),
	gotodone: z.boolean().optional().describe("Go To Done"),
	ondone: z.string().optional().describe("On Done"),
	callbacks: z.string().optional().describe("Callbacks"),
	segdat: z.any().nullable().optional().describe("Segment DAT"),
	segmethod: z.string().optional().describe("Segment Method"),
	segunits: z.string().optional().describe("Segment Units"),
	segsendtime: z.string().optional().describe("Segment Send Time"),
	channelcolumns: z.string().optional().describe("Channel Columns"),
	interpolation: z.string().optional().describe("Interpolation"),
	infocolumns: z.string().optional().describe("Info Columns"),
	gotoprevseg: z.boolean().optional().describe("Go To Previous Segment"),
	gotonextseg: z.boolean().optional().describe("Go To Next Segment"),
	subrange: z.boolean().optional().describe("Sub Range"),
	substart: z.number().optional().describe("Sub Start"),
	substartunits: z.string().optional().describe("Sub Start Units"),
	subend: z.number().optional().describe("Sub End"),
	subendunits: z.string().optional().describe("Sub End Units"),
	subendaction: z.string().optional().describe("Sub End Action"),
	outfraction: z.boolean().optional().describe("Output Fraction"),
	outtimercount: z.string().optional().describe("Output Timer Count"),
	outtimeractive: z.boolean().optional().describe("Output Timer Active"),
	outtimerpulse: z.boolean().optional().describe("Output Timer Pulse"),
	outdelayfraction: z.boolean().optional().describe("Output Delay Fraction"),
	outdelaycount: z.string().optional().describe("Output Delay Count"),
	outinit: z.boolean().optional().describe("Output Initialize"),
	outready: z.boolean().optional().describe("Output Ready"),
	outreadypulse: z.boolean().optional().describe("Output Ready Pulse"),
	outrunning: z.boolean().optional().describe("Output Running"),
	outdone: z.boolean().optional().describe("Output Done"),
	outdonepulse: z.boolean().optional().describe("Output Done Pulse"),
	outcycle: z.boolean().optional().describe("Output Cycle"),
	outcyclepulse: z.boolean().optional().describe("Output Cycle Pulse"),
	outcycleplusfraction: z
		.boolean()
		.optional()
		.describe("Output Cycle Plus Fraction"),
	outseg: z.boolean().optional().describe("Output Segment"),
	outsegpulse: z.boolean().optional().describe("Output Segment Pulse"),
	outsegplusfraction: z
		.boolean()
		.optional()
		.describe("Output Segment Plus Fraction"),
	outlength: z.string().optional().describe("Output Length"),
	outcumulativecount: z.string().optional().describe("Output Cumulative Count"),
	outplayingcount: z.string().optional().describe("Output Playing Count"),
	outrunningcount: z.string().optional().describe("Output Running Count"),
	outmastercount: z.string().optional().describe("Output Master Count"),
	extchop: z.any().nullable().optional().describe("External CHOP"),
	extunits: z.string().optional().describe("External Units"),
	extchannel: z.string().optional().describe("External Channel"),
	exttcop: z.any().nullable().optional().describe("External TCOP"),
	extstartoff: z.number().optional().describe("External Start Offset"),
	extinitoff: z.number().optional().describe("External Initialize Offset"),
	rate: z.number().optional().describe("Rate"),
});
