import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const topto = createCHOPSchema({
	top: z.any().nullable().optional().describe("TOP"),
	downloadtype: z.string().optional().describe("Download Type"),
	r: z.string().optional().describe("R"),
	g: z.string().optional().describe("G"),
	b: z.string().optional().describe("B"),
	a: z.string().optional().describe("A"),
	singleset: z.boolean().optional().describe("Single Set"),
	excludenans: z.boolean().optional().describe("Exclude NaNs"),
	activechannel: z.string().optional().describe("Active Channel"),
	rgbaunit: z.string().optional().describe("RGBA Unit"),
	crop: z.string().optional().describe("Crop"),
	uvunits: z.string().optional().describe("UV Units"),
	ustart: z.number().optional().describe("U Start"),
	uend: z.number().optional().describe("U End"),
	vstart: z.number().optional().describe("V Start"),
	vend: z.number().optional().describe("V End"),
	interp: z.string().optional().describe("Interpolation"),
	imageleft: z.string().optional().describe("Image Left"),
	imageright: z.string().optional().describe("Image Right"),
	imagebottom: z.string().optional().describe("Image Bottom"),
	imagetop: z.string().optional().describe("Image Top"),
	defcolorr: z.number().optional().describe("Default Color R"),
	defcolorg: z.number().optional().describe("Default Color G"),
	defcolorb: z.number().optional().describe("Default Color B"),
	defcolora: z.number().optional().describe("Default Color A"),
	start: z.number().optional().describe("Start"),
	startunit: z.string().optional().describe("Start Unit"),
	rate: z.number().optional().describe("Rate"),
	left: z.string().optional().describe("Left Boundary"),
	right: z.string().optional().describe("Right Boundary"),
	defval: z.number().optional().describe("Default Value"),
});
