import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const transform = createCHOPSchema({
	custinputorders: z.boolean().optional().describe("Custom Input Orders"),
	inxord: z.string().optional().describe("Input Transform Order"),
	inrord: z.string().optional().describe("Input Rotation Order"),
	input0preop: z.string().optional().describe("Input 0 Pre-op"),
	input1preop: z.string().optional().describe("Input 1 Pre-op"),
	inputoperation: z.string().optional().describe("Input Operation"),
	inputweight: z.number().optional().describe("Input Weight"),
	xord: z.string().optional().describe("Transform Order"),
	rord: z.string().optional().describe("Rotation Order"),
	tx: z.number().optional().describe("Translate X"),
	ty: z.number().optional().describe("Translate Y"),
	tz: z.number().optional().describe("Translate Z"),
	rx: z.number().optional().describe("Rotate X"),
	ry: z.number().optional().describe("Rotate Y"),
	rz: z.number().optional().describe("Rotate Z"),
	sx: z.number().optional().describe("Scale X"),
	sy: z.number().optional().describe("Scale Y"),
	sz: z.number().optional().describe("Scale Z"),
	px: z.number().optional().describe("Pivot X"),
	py: z.number().optional().describe("Pivot Y"),
	pz: z.number().optional().describe("Pivot Z"),
	trspreop: z.string().optional().describe("TRS Pre-op"),
	xformmatrixop: z.any().nullable().optional().describe("Transform Matrix Op"),
	lookat: z.any().nullable().optional().describe("Look At"),
	upvectorx: z.number().optional().describe("Up Vector X"),
	upvectory: z.number().optional().describe("Up Vector Y"),
	upvectorz: z.number().optional().describe("Up Vector Z"),
	forwarddir: z.string().optional().describe("Forward Direction"),
	xformpagepreop: z.string().optional().describe("Transform Page Pre-op"),
	operation: z.string().optional().describe("Operation"),
	weight: z.number().optional().describe("Weight"),
	postop: z.string().optional().describe("Post-op"),
	output: z.string().optional().describe("Output"),
	determ: z.boolean().optional().describe("Determinant"),
	unmatchedchans: z.string().optional().describe("Unmatched Channels"),
	custoutputorders: z.boolean().optional().describe("Custom Output Orders"),
	outxord: z.string().optional().describe("Output Transform Order"),
	outrord: z.string().optional().describe("Output Rotation Order"),
	includeorderchans: z.boolean().optional().describe("Include Order Channels"),
	continuousrotations: z.boolean().optional().describe("Continuous Rotations"),
	usehint: z.boolean().optional().describe("Use Hint"),
	hintx: z.number().optional().describe("Hint X"),
	hinty: z.number().optional().describe("Hint Y"),
	hintz: z.number().optional().describe("Hint Z"),
});
