import { z } from "zod";
import { createCHOPSchema } from "./utils.js";

export const trigger = createCHOPSchema({
	threshold: z.boolean().optional().describe("Threshold"),
	threshup: z.number().optional().describe("Threshold Up"),
	threshdown: z.number().optional().describe("Threshold Down"),
	retrigger: z.number().optional().describe("Retrigger"),
	retriggerunit: z.string().optional().describe("Retrigger Unit"),
	mintrigger: z.number().optional().describe("Min Trigger"),
	mintriggerunit: z.string().optional().describe("Min Trigger Unit"),
	triggeron: z.string().optional().describe("Trigger On"),
	multitrigger: z.string().optional().describe("Multi Trigger"),
	clamppeak: z.boolean().optional().describe("Clamp Peak"),
	triggerpulse: z.boolean().optional().describe("Trigger Pulse"),
	updateonce: z.boolean().optional().describe("Update Once"),
	complete: z.boolean().optional().describe("Complete"),
	remainder: z.string().optional().describe("Remainder"),
	delay: z.number().optional().describe("Delay"),
	delayunit: z.string().optional().describe("Delay Unit"),
	attack: z.number().optional().describe("Attack"),
	attackunit: z.string().optional().describe("Attack Unit"),
	ashape: z.string().optional().describe("Attack Shape"),
	peak: z.number().optional().describe("Peak"),
	peaklen: z.number().optional().describe("Peak Length"),
	peaklenunit: z.string().optional().describe("Peak Length Unit"),
	decay: z.number().optional().describe("Decay"),
	decayunit: z.string().optional().describe("Decay Unit"),
	dshape: z.string().optional().describe("Decay Shape"),
	sustain: z.number().optional().describe("Sustain"),
	minsustain: z.number().optional().describe("Min Sustain"),
	minsustainunit: z.string().optional().describe("Min Sustain Unit"),
	release: z.number().optional().describe("Release"),
	releaseunit: z.string().optional().describe("Release Unit"),
	rshape: z.string().optional().describe("Release Shape"),
	channame: z.string().optional().describe("Channel Name"),
	specifyrate: z.boolean().optional().describe("Specify Rate"),
	rate: z.number().optional().describe("Rate"),
});
