import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { parse, stringify } from "yaml";

const repo = fileURLToPath(new URL("../", import.meta.url));
const source = join(repo, "plugin/touchdesigner");

export async function buildOpenaiPlugin({
	out = join(repo, "dist/openai-plugin"),
	host = "http://127.0.0.1",
	port = "9981",
	appId,
} = {}) {
	let url;
	try {
		url = new URL(host);
	} catch {
		throw new Error("host must be an HTTP(S) URL, e.g. http://127.0.0.1");
	}
	if (
		!["http:", "https:"].includes(url.protocol) ||
		url.username ||
		url.password
	) {
		throw new Error("host must be an HTTP(S) URL without credentials");
	}
	// touchdesigner-mcp-server builds its base URL as `${host}:${port}`, so the
	// host must stop at the hostname. Reject explicit ports (including :80/:443,
	// which URL.port normalizes away) and anything beyond an optional root slash;
	// `\` counts because the URL parser treats it as `/` for http(s).
	if (!/^https?:\/\/(?:\[[^\]]+\]|[^:/?#\\]+)\/?$/i.test(host)) {
		throw new Error(
			"host must contain only the scheme and hostname; use --port separately (no path, query, or fragment)",
		);
	}
	host = url.origin;
	if (!/^\d+$/.test(String(port)) || Number(port) < 1 || Number(port) > 65535) {
		throw new Error("port must be an integer from 1 to 65535");
	}
	if (appId && !/^plugin_asdk_app[a-zA-Z0-9_-]+$/.test(appId)) {
		throw new Error(
			"app-id must be the registered plugin_asdk_app technical ID",
		);
	}
	const root = resolve(out);
	const plugin = join(root, "plugins/touchdesigner");
	// Refuse to write into a non-empty directory unless our marker is present;
	// an empty one is claimed. Once marked, only this plugin's tree and the
	// marketplace file are replaced.
	const markerName = ".touchdesigner-openai-build";
	const marker = join(root, markerName);
	await mkdir(root, { recursive: true });
	const entries = await readdir(root);
	if (entries.length && !entries.includes(markerName)) {
		throw new Error("output directory is not empty or owned by this builder");
	}
	await writeFile(marker, "Generated by scripts/buildOpenaiPlugin.mjs\n");
	await rm(plugin, { force: true, recursive: true });
	const original = JSON.parse(
		await readFile(join(source, ".claude-plugin/plugin.json"), "utf8"),
	);
	const manifest = {
		author: original.author,
		description:
			"Inspect, build, debug, and verify TouchDesigner projects with MCP tools and reusable workflows.",
		homepage: original.homepage,
		keywords: original.keywords,
		license: original.license,
		name: original.name,
		repository: original.repository,
		skills: "./skills/",
		version: original.version,
		...(appId ? { apps: "./.app.json" } : { mcpServers: "./.mcp.json" }),
		interface: {
			capabilities: ["Read", "Write"],
			category: "Productivity",
			defaultPrompt: [
				"Check my TouchDesigner connection",
				"Show my TouchDesigner project structure",
				"Capture my TOP output",
			],
			developerName: original.author.name,
			displayName: "TouchDesigner",
			longDescription:
				"Connect to TouchDesigner to inspect nodes, build networks, debug errors, capture TOP images, and measure cook times.",
			shortDescription: "Build and inspect live TouchDesigner projects",
			websiteURL: original.homepage,
		},
	};
	async function json(path, data) {
		await mkdir(dirname(path), { recursive: true });
		await writeFile(path, `${JSON.stringify(data, null, "\t")}\n`);
	}
	await json(join(plugin, ".codex-plugin/plugin.json"), manifest);
	if (appId) {
		await json(join(plugin, ".app.json"), {
			apps: { touchdesigner: { id: appId } },
		});
	} else {
		const claudeMcp = JSON.parse(
			await readFile(join(source, ".mcp.json"), "utf8"),
		);
		const values = {
			touchdesigner_host: host,
			touchdesigner_port: String(port),
		};
		const server = claudeMcp.touchdesigner;
		server.args = server.args.map((arg) =>
			arg.replace(/\$\{user_config\.([^}]+)\}/g, (_, key) => {
				if (!(key in values)) throw new Error(`Unknown Claude option: ${key}`);
				return values[key];
			}),
		);
		await json(join(plugin, ".mcp.json"), {
			mcpServers: { touchdesigner: server },
		});
	}
	await cp(join(source, "skills"), join(plugin, "skills"), { recursive: true });
	for (const skill of await readdir(join(plugin, "skills"))) {
		const path = join(plugin, "skills", skill, "SKILL.md");
		const text = await readFile(path, "utf8");
		const match = text.match(/^---\n([\s\S]*?)\n---\n/);
		if (!match) throw new Error(`Missing frontmatter: ${skill}`);
		const { name, description } = parse(match[1]);
		const body = text
			.slice(match[0].length)
			.replaceAll("mcp__plugin_touchdesigner_touchdesigner__", "");
		const context =
			"\n## Client integration\n\nUse the connected TouchDesigner server's tools by logical name; discover the actual client namespace instead of constructing a Claude tool prefix. Slash-command examples also work as natural-language requests for the named skill. After any network mutation, read back affected parameters, check `get_td_node_errors`, and inspect `get_top_image` for TOP output when relevant. Do not rely on a post-tool hook to remind you.\n";
		await writeFile(
			path,
			`---\n${stringify({ description, name })}---\n${context}${body}`,
		);
	}
	await cp(join(repo, "docs/openai-plugin.md"), join(plugin, "README.md"));
	await json(join(root, ".agents/plugins/marketplace.json"), {
		interface: { displayName: "TouchDesigner" },
		name: "touchdesigner-openai",
		plugins: [
			{
				category: "Productivity",
				name: manifest.name,
				policy: { authentication: "ON_INSTALL", installation: "AVAILABLE" },
				source: { path: "./plugins/touchdesigner", source: "local" },
			},
		],
	});
	return plugin;
}

if (
	process.argv[1] &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
	const { values } = parseArgs({
		options: {
			"app-id": { type: "string" },
			host: { type: "string" },
			out: { type: "string" },
			port: { type: "string" },
		},
	});
	console.log(await buildOpenaiPlugin({ ...values, appId: values["app-id"] }));
}
