#!/usr/bin/env node
/**
 * Inject version from package.json into Python module
 *
 * This script ensures the Python server has the same API version
 * as the Node.js client by reading from package.json (single source of truth)
 * and writing to a Python version file.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import YAML, { type YAMLMap } from "yaml";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read package.json
const packageJson = JSON.parse(
	readFileSync(`${__dirname}/../../package.json`, "utf-8"),
);

const version = packageJson.version;

// Python version file path
const versionFilePath = `${__dirname}/../modules/mcp/__version__.py`;

// Ensure directory exists
const versionFileDir = dirname(versionFilePath);
mkdirSync(versionFileDir, { recursive: true });

// Generate Python file content
const pythonContent = `# Auto-generated by td/script/injectVersion.ts - DO NOT EDIT
# This file is generated during build process from package.json

__version__ = "${version}"
`;

// Write to file
writeFileSync(versionFilePath, pythonContent, "utf-8");

const updateTextFile = (
	filePath: string,
	updater: (content: string) => string,
) => {
	const before = readFileSync(filePath, "utf-8");
	const after = updater(before);
	if (after !== before) {
		writeFileSync(filePath, after, "utf-8");
		console.log(`✓ Updated ${filePath}`);
	} else {
		console.log(`● No change for ${filePath}`);
	}
};

// Update OpenAPI schema version
updateTextFile(`${__dirname}/../../src/api/index.yml`, (content) => {
	const doc = YAML.parseDocument(content);
	const info = doc.get("info") as YAMLMap;
	if (info && typeof info === "object" && "set" in info) {
		info.set("version", version);
	}
	return doc.toString();
});

// Update MCP Bundle manifest
updateTextFile(`${__dirname}/../../mcpb/manifest.json`, (content) => {
	const manifest = JSON.parse(content);
	manifest.version = version;
	return `${JSON.stringify(manifest, null, 2)}\n`;
});

// Update Python project metadata
updateTextFile(`${__dirname}/../../pyproject.toml`, (content) =>
	content.replace(/version\s*=\s*"[^"]+"/, `version = "${version}"`),
);

// Update MCP registry server definition
updateTextFile(`${__dirname}/../../server.json`, (content) => {
	const serverConfig = JSON.parse(content);
	serverConfig.version = version;
	if (Array.isArray(serverConfig.packages)) {
		for (const pkg of serverConfig.packages) {
			if (pkg && typeof pkg === "object") {
				if (pkg.version) {
					pkg.version = version;
				}
				if (typeof pkg.identifier === "string") {
					pkg.identifier = pkg.identifier
						.replace(/(releases\/download\/v)[^/]+/, `$1${version}`)
						.replace(/(touchdesigner-mcp)(\.mcpb)/, "$1$2");
				}
			}
		}
	}
	return `${JSON.stringify(serverConfig, null, 2)}\n`;
});

console.log(`✓ Injected version ${version} into ${versionFilePath}`);
