#!/usr/bin/env node
/**
 * Inject version from package.json into Python module
 *
 * This script ensures the Python server has the same API version
 * as the Node.js client by reading from package.json (single source of truth)
 * and writing to a Python version file.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read package.json
const packageJson = JSON.parse(
	readFileSync(`${__dirname}/../../package.json`, "utf-8"),
);

const version = packageJson.version;

// Python version file path
const versionFilePath = `${__dirname}/../modules/mcp/__version__.py`;

// Ensure directory exists
const versionFileDir = dirname(versionFilePath);
mkdirSync(versionFileDir, { recursive: true });

// Generate Python file content
const content = `# Auto-generated by td/script/injectVersion.js - DO NOT EDIT
# This file is generated during build process from package.json

__version__ = "${version}"
`;

// Write to file
writeFileSync(versionFilePath, content, "utf-8");

console.log(`✓ Injected version ${version} into ${versionFilePath}`);
